# Generated by Django 2.2 on 2020-03-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15)),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=65)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login.Student')),
            ],
        ),
    ]
