<<<<<<< HEAD
# Generated by Django 2.2 on 2020-03-26 21:01
=======
# Generated by Django 2.2 on 2020-03-26 22:31
>>>>>>> e73b72a06f48a666ed4b99394e3957b6e3753997

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
