# Generated by Django 2.2 on 2020-03-25 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200325_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login.Student'),
        ),
    ]
