# Generated by Django 2.2 on 2020-03-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200326_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
    ]
