# Generated by Django 2.2 on 2020-03-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_student'),
        ('LearnApp', '0002_auto_20200326_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='login.User'),
            preserve_default=False,
        ),
    ]
